### ISSUE TITLE
Some "Unique Element" bosses on map viewer are different from ingame

### ISSUE THREAD

**Issue by Aceship** [MurakumoIndustries/Frontier#3]
several bosses like レントラー are different between ingame and map viewer
example : 
![image](https://user-images.githubusercontent.com/5337323/43681092-1483d870-9874-11e8-86f8-30d8c3fcaeec.png)
![firefox_2018-08-05_05-53-34](https://user-images.githubusercontent.com/5337323/43681093-1b45d5a0-9874-11e8-982d-1379ce30bba7.png)

**Comment by WindWT** [comment]
can reproduce on right bottom hex of 97|トライプレイン宙域
don't know how to fix it though, can't find notable difference between hex with special boss and hex with normal boss

**Comment by WindWT** [comment]
fixed
